name: JASPAR-UCSC-tracks
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.86
  - click=8.3.0
  - click-option-group=0.5.6
  - genomepy=0.16.3
  - git=2.51.2
  - numpy=2.2.6
  - perl-math-round=0.07
  - pip=25.3
  - pyfaidx=0.9.0.3
  - python=3.10
  - tqdm=4.67.1
  - ucsc-bedtobigbed
  - ucsc-bigbedtobed
  - ucsc-twobittofa
